package com.example.demo.entity;
// Generated May 20, 2020 1:50:13 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChiTietFeedbackOnline generated by hbm2java
 */
@Entity
@Table(name = "ChiTietFeedback_Online", catalog = "db_feedback")
public class ChiTietFeedbackOnline implements java.io.Serializable {

	private Integer ctFbMa;
	private Feedback feedback;
	private String ctFbNoiDung;
	private String ctFbLoai;
	private Set<PhanHoiFeedBack> phanHoiFeedBacks = new HashSet<PhanHoiFeedBack>(0);

	public ChiTietFeedbackOnline() {
	}

	public ChiTietFeedbackOnline(Feedback feedback, String ctFbNoiDung, String ctFbLoai,
			Set<PhanHoiFeedBack> phanHoiFeedBacks) {
		this.feedback = feedback;
		this.ctFbNoiDung = ctFbNoiDung;
		this.ctFbLoai = ctFbLoai;
		this.phanHoiFeedBacks = phanHoiFeedBacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CtFb_Ma", unique = true, nullable = false)
	public Integer getCtFbMa() {
		return this.ctFbMa;
	}

	public void setCtFbMa(Integer ctFbMa) {
		this.ctFbMa = ctFbMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Fb_Ma")
	public Feedback getFeedback() {
		return this.feedback;
	}

	public void setFeedback(Feedback feedback) {
		this.feedback = feedback;
	}

	@Column(name = "CtFb_NoiDung", length = 1000)
	public String getCtFbNoiDung() {
		return this.ctFbNoiDung;
	}

	public void setCtFbNoiDung(String ctFbNoiDung) {
		this.ctFbNoiDung = ctFbNoiDung;
	}

	@Column(name = "CtFb_Loai", length = 100)
	public String getCtFbLoai() {
		return this.ctFbLoai;
	}

	public void setCtFbLoai(String ctFbLoai) {
		this.ctFbLoai = ctFbLoai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chiTietFeedbackOffline")
	public Set<PhanHoiFeedBack> getPhanHoiFeedBacks() {
		return this.phanHoiFeedBacks;
	}

	public void setPhanHoiFeedBacks(Set<PhanHoiFeedBack> phanHoiFeedBacks) {
		this.phanHoiFeedBacks = phanHoiFeedBacks;
	}

}
