package com.example.demo.entity;
// Generated May 20, 2020 1:50:13 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DanhSachLopHoc generated by hbm2java
 */
@Entity
@Table(name = "DanhSachLopHoc", catalog = "db_feedback")
public class DanhSachLopHoc implements java.io.Serializable {

	private Integer dslhMa;
	private TaiKhoan taiKhoan;

	public DanhSachLopHoc() {
	}

	public DanhSachLopHoc(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Dslh_Ma", unique = true, nullable = false)
	public Integer getDslhMa() {
		return this.dslhMa;
	}

	public void setDslhMa(Integer dslhMa) {
		this.dslhMa = dslhMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Email")
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

}
