package com.example.demo.entity;
// Generated May 20, 2020 1:50:13 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "Feedback", catalog = "db_feedback")
public class Feedback implements java.io.Serializable {

	private Integer fbMa;
	private KhoaHoc khoaHoc;
	private Set<ChiTietFeedbackOnline> chiTietFeedbackOnlines = new HashSet<ChiTietFeedbackOnline>(0);
	private Set<ChiTietFeedbackSeminar> chiTietFeedbackSeminars = new HashSet<ChiTietFeedbackSeminar>(0);
	private Set<ChiTietFeedbackOffline> chiTietFeedbackOfflines = new HashSet<ChiTietFeedbackOffline>(0);

	public Feedback() {
	}

	public Feedback(KhoaHoc khoaHoc, Set<ChiTietFeedbackOnline> chiTietFeedbackOnlines,
			Set<ChiTietFeedbackSeminar> chiTietFeedbackSeminars, Set<ChiTietFeedbackOffline> chiTietFeedbackOfflines) {
		this.khoaHoc = khoaHoc;
		this.chiTietFeedbackOnlines = chiTietFeedbackOnlines;
		this.chiTietFeedbackSeminars = chiTietFeedbackSeminars;
		this.chiTietFeedbackOfflines = chiTietFeedbackOfflines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Fb_Ma", unique = true, nullable = false)
	public Integer getFbMa() {
		return this.fbMa;
	}

	public void setFbMa(Integer fbMa) {
		this.fbMa = fbMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Kh_Ma")
	public KhoaHoc getKhoaHoc() {
		return this.khoaHoc;
	}

	public void setKhoaHoc(KhoaHoc khoaHoc) {
		this.khoaHoc = khoaHoc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedback")
	public Set<ChiTietFeedbackOnline> getChiTietFeedbackOnlines() {
		return this.chiTietFeedbackOnlines;
	}

	public void setChiTietFeedbackOnlines(Set<ChiTietFeedbackOnline> chiTietFeedbackOnlines) {
		this.chiTietFeedbackOnlines = chiTietFeedbackOnlines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedback")
	public Set<ChiTietFeedbackSeminar> getChiTietFeedbackSeminars() {
		return this.chiTietFeedbackSeminars;
	}

	public void setChiTietFeedbackSeminars(Set<ChiTietFeedbackSeminar> chiTietFeedbackSeminars) {
		this.chiTietFeedbackSeminars = chiTietFeedbackSeminars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedback")
	public Set<ChiTietFeedbackOffline> getChiTietFeedbackOfflines() {
		return this.chiTietFeedbackOfflines;
	}

	public void setChiTietFeedbackOfflines(Set<ChiTietFeedbackOffline> chiTietFeedbackOfflines) {
		this.chiTietFeedbackOfflines = chiTietFeedbackOfflines;
	}

}
