package com.example.demo.entity;
// Generated May 20, 2020 3:00:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhanHoiFeedBack generated by hbm2java
 */
@Entity
@Table(name = "PhanHoiFeedBack", catalog = "db_feedback")
public class PhanHoiFeedBack implements java.io.Serializable {

	private Integer phFbMa;
	private ChiTietFeedbackOffline chiTietFeedbackOffline;
	private ChiTietFeedbackOnline chiTietFeedbackOnline;
	private ChiTietFeedbackSeminar chiTietFeedbackSeminar;
	private TaiKhoan taiKhoan;
	private String phFbNoiDung;

	public PhanHoiFeedBack() {
	}

	public PhanHoiFeedBack(ChiTietFeedbackOffline chiTietFeedbackOffline, ChiTietFeedbackOnline chiTietFeedbackOnline,
			ChiTietFeedbackSeminar chiTietFeedbackSeminar, TaiKhoan taiKhoan, String phFbNoiDung) {
		this.chiTietFeedbackOffline = chiTietFeedbackOffline;
		this.chiTietFeedbackOnline = chiTietFeedbackOnline;
		this.chiTietFeedbackSeminar = chiTietFeedbackSeminar;
		this.taiKhoan = taiKhoan;
		this.phFbNoiDung = phFbNoiDung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PhFb_Ma", unique = true, nullable = false)
	public Integer getPhFbMa() {
		return this.phFbMa;
	}

	public void setPhFbMa(Integer phFbMa) {
		this.phFbMa = phFbMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CtFb_Ma")
	public ChiTietFeedbackOffline getChiTietFeedbackOffline() {
		return this.chiTietFeedbackOffline;
	}

	public void setChiTietFeedbackOffline(ChiTietFeedbackOffline chiTietFeedbackOffline) {
		this.chiTietFeedbackOffline = chiTietFeedbackOffline;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CtFb_Ma", insertable = false, updatable = false)
	public ChiTietFeedbackOnline getChiTietFeedbackOnline() {
		return this.chiTietFeedbackOnline;
	}

	public void setChiTietFeedbackOnline(ChiTietFeedbackOnline chiTietFeedbackOnline) {
		this.chiTietFeedbackOnline = chiTietFeedbackOnline;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CtFb_Ma", insertable = false, updatable = false)
	public ChiTietFeedbackSeminar getChiTietFeedbackSeminar() {
		return this.chiTietFeedbackSeminar;
	}

	public void setChiTietFeedbackSeminar(ChiTietFeedbackSeminar chiTietFeedbackSeminar) {
		this.chiTietFeedbackSeminar = chiTietFeedbackSeminar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Email")
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "PhFb_NoiDung", length = 500)
	public String getPhFbNoiDung() {
		return this.phFbNoiDung;
	}

	public void setPhFbNoiDung(String phFbNoiDung) {
		this.phFbNoiDung = phFbNoiDung;
	}

}
