package com.example.demo.entity;
// Generated May 20, 2020 3:00:35 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "UserRole", catalog = "db_feedback")
public class UserRole implements java.io.Serializable {

	private int urMa;
	private String urRole;
	private Set<TaiKhoan> taiKhoans = new HashSet<TaiKhoan>(0);

	public UserRole() {
	}

	public UserRole(int urMa) {
		this.urMa = urMa;
	}

	public UserRole(int urMa, String urRole, Set<TaiKhoan> taiKhoans) {
		this.urMa = urMa;
		this.urRole = urRole;
		this.taiKhoans = taiKhoans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Ur_Ma", unique = true, nullable = false)
	public int getUrMa() {
		return this.urMa;
	}

	public void setUrMa(int urMa) {
		this.urMa = urMa;
	}

	@Column(name = "Ur_Role", length = 10)
	public String getUrRole() {
		return this.urRole;
	}

	public void setUrRole(String urRole) {
		this.urRole = urRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<TaiKhoan> getTaiKhoans() {
		return this.taiKhoans;
	}

	public void setTaiKhoans(Set<TaiKhoan> taiKhoans) {
		this.taiKhoans = taiKhoans;
	}

}
